name: Build package

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Build
      run: make fetch trixie

    - name: Store package
      uses: actions/upload-artifact@v5
      with:
        name: emacs-pgtk
        path: ./packages/emacs/emacs-pgtk_*.deb
